<?php
class Blocks {
	public function getID($request) {
		$DB = array(
		1 => array("Stone", "Rock"),
		2 => 'Grass',
		3 => array("Dirt", "Earth"),
		4 => array("Cobblestone", "Cobble"),
		5 => array("WoodenPlank", "Wood", "Plank"),
		6 => 'Sapling',
		7 => array("Bedrock", "Adminium", "Solid"),
		8 => 'Water',
		9 => 'StationaryWater',
		10 => 'Lava',
		11 => 'StationaryLava',
        12 => 'Sand',
        13 => 'Gravel',
        14 => 'GoldOre',
        15 => 'IronOre',
        16 => 'CoalOre',
        17 => array("Log", "LogBlock"),
        '17:1' => array("PineLog", "RedwoodLog", "DarkLog"),
        '17:2' => 'BirchLog',
        18 => array("Leaves", "LeafBlock"),
        '18:1' => array("BirchLeaves", "BirchLeafBlock"),
        '18:2' => array("PineLeaves", "RedwoodLeaves", "DarkLeaves"),
        19 => 'Sponge',
        20 => 'Glass',
        21 => array("LapisLazuliOre", "LapisOre", "BlueOre"),
        22 => array("LapisLazuliBlock", "LapisBlock", "BlockOfLapis"),
        23 => 'Dispenser',
        24 => 'Sandstone',
        25 => array("Noteblock", "MusicBlock"),
        26 => 'BedBlock',
        27 => array("PoweredRail", "BoosterTrack", "BoosterRail"),
        28 => 'DetectorRail',
        29 => array("StickyPiston", "PushMePullYou"),
        30 => array("Web", "CobWeb", "SpiderWeb"),
        31 => array("DeadShrub", "Grass", "TallGrass"),
        '31:1' => 'TallGrass',
        '31:2' => 'Fern',
        32 => 'DeadShrub',
        33 => array("Piston", "PushMeNotPullYou"),
        34 => 'PistonHead',
        35 => array("Cloth", "Wool", "WoolBlock"),
        '35:1' => 'OrangeWool',
        '35:2' => array("MagentaWool", "PinkWool"),
        '35:3' => array("LightBlueWool", "BlueWool"),
        '35:4' => 'YellowWool',
        '35:5' => array("LimeWool", "LightGreenWool", "BrightGreenWool", "GreenWool"),
        '35:6' => array("PinkWool", "LightPinkWool"),
        '35:7' => array("DarkGreyWool", "DarkGrayWool", "GrayWool", "GreyWool"),
        '35:8' => array("LightGreyWool", "LightGrayWool", "GrayWool", "GreyWool"),
        '35:9' => array("AquaGreenWool", "AquaWool"),
        '35:10' => 'PurpleWool',
        '35:11' => array("BlueWool", "DarkBlueWool", "CyanWool"),
        '35:12' => 'BrownWool',
        '35:13' => array("GreenWool", "DarkGreenWool"),
        '35:14' => 'RedWool',
        '35:15' => 'BlackWool',
        36 => 'Nothing',
        37 => array("YellowFlower", "Flower"),
        38 => array("RedFlower", "Flower"),
        39 => array("BrownMushroom", "Mushroom"),
        40 => array("RedMushroom", "Mushroom", "1UP"),
        41 => 'GoldBlock',
        42 => 'IronBlock',
        43 => array("DoubleStep", "StoneStep"),
        '43:1' => array("SandstoneDoubleStep", "SandstoneStepBlock", "DoubleStep"),
        '43:2' => array("WoodDoubleStep", "DoubleStep"),
        '43:3' => array("CobblestoneDoubleStep", "CobbleDoubleStep", "DoubleStep"),
        43 => 'Step',
        '43:1' => array("SandstoneStep", "Step"),
        '43:2' => array("WoodStep", "Step"),
        '43:3' => array("CobbleStep", "Step"),
        45 => 'BrickBlock',
        46 => 'TNT',
        47 => 'Bookshelf',
        48 => array("MossyCobblestone", "MossyCobble", "MossStone"),
        49 => 'Obsidian',
        50 => 'Torch',
        51 => 'Fire',
        52 => array("MobSpawner", "Spawner"),
        53 => array("WoodStairs", "WoodenStairs"),
        54 => 'Chest',
        55 => 'RedstoneWire',
        56 => 'DiamondOre',
        57 => 'DiamondBlock',
        58 => array("Workbench", "CraftingBench"),
        59 => array("Seeds", "Wheat"),
        60 => 'Farmland',
        61 => 'Furnace',
        62 => array("Furnace(On)", "BurningFurnace"),
        63 => 'SignPost',
        64 => array("HalfWoodDoor", "HalfDoor"),
        65 => 'Ladder',
        66 => array("Rail", "MineTrack"),
        67 => array("CobbleStairs", "CobblestoneStairs"),
        68 => 'WallSign',
        69 => 'Lever',
        70 => 'StonePressurePlate',
        71 => array("HalfIronDoor", "HalfDoor"),
        72 => 'WoodPressurePlate',
        73 => 'RedstoneOre',
        74 => 'GlowingRedstoneOre',
        75 => 'RedstoneTorch(Off)',
        76 => array("RedstoneTorch", "RedstoneTorch(On)"),
        77 => 'Button',
        78 => 'Snow',
        79 => array("Ice", "IceBlock"),
        80 => 'SnowBlock',
        81 => 'Cactus',
        82 => array("ClayBlock", "Clay"),
        83 => 'ReedBlock',
        84 => array("Jukebox", "Musicbox"),
        85 => 'Fence',
        86 => 'Pumpkin',
        87 => 'Netherrack',
        88 => array("SoulSand", "SlowSand"),
        89 => array("Glowstone", "Lightstone"),
        90 => 'Portal',
        91 => array("Jack-O-Lantern", "JackOLantern"),
        92 => 'CakeBlock',
        93 => 'Repeater(Off)',
        94 => 'Repeater(On)',
        95 => array("MannCoSupplyCrate", "MannCoChest", "LockedChest", "SteveCoSupplyCreate", "SteveCo.SupplyCrate", "AprilFoolsChest", "SteveCoChest", "SteveCo.Chest", "LightEmittingBlockOfLightness"),
		96 => array('TrapDoor', 'Hatch'));
		$block_name = strtolower($request);
		foreach ($DB as $id => $value) {
			if (!(is_array($value))) {
				if (strtolower($value) == $block_name) {
					$result = $id;
				}
			}
			else {
				foreach ($value as $value_array => $name) {
					if (strtolower($name) == $block_name)
						$result = $id;
				}
			}
		}
		return $result;
	}
}